<a href="https://colab.research.google.com/github/Arthur6363/Data-Science-ML/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [9]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [12]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [16]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [19]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y ,random_state=63, test_size=0.2)

In [24]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [48]:
from tensorflow import keras

In [63]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [76]:
ann = Sequential()
ann.add(Dense(6, activation='relu'))
ann.add(Dense(6, activation='relu'))
ann.add(Dense(1))
ann.compile(optimizer='adam', loss='mean_squared_error')
ann.fit(x_train, y_train, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.2118
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1628
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1553
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1495
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1452
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1426
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1407
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1393
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1379
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1372
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.1362
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.1347
Epoch 13/100


In [77]:
y_pred = ann.predict(x_test)

63/63 [==============================] - 0s 3ms/step


In [78]:
y_pred = (y_pred>0.5)

In [80]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm

array([[   2, 1600],
       [   0,  398]])

In [81]:
accuracy_score(y_test, y_pred)

0.2